### ISSUE TITLE
Interested in ZoKrates. Can we talk its hard to reach you unable to find email. Hence i start a issue here. Sorry.

### ISSUE THREAD

**Issue by AnvayMTL** [JacobEberhardt/documents#1]

**Comment by TPei** [comment]
Hey, just fyi, there's a gitter channel for ZoKrates: https://gitter.im/ZoKrates/Lobby

**Comment by JacobEberhardt** [comment]
Email is on the slides and ZoKrates gitter is the correct entry point.
